tello/aruco_opencv_map:
  ros__parameters:
    header:
      frame_id: odom
    # markers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 18]
    markers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 18]

    marker_1:
      pose:
        position:
          x: 0.90
          y: 0.00
          z: 1.10
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_2:
      pose:
        position:
          x: 2.10
          y: 0.50
          z: 1.00
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_3:
      pose:
        position:
          x: 2.10
          y: 0.00
          z: 1.30
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_4:
      pose:
        position:
          x: 2.10
          y: -0.50
          z: 1.60
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_5:
      pose:
        position:
          x: 3.17
          y: 0.00
          z: 1.20
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_6:
      pose:
        position:
          x: 7.36
          y: 0.00
          z: 1.01
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_7:
      pose:
        position:
          x: 6.41
          y: 0.00
          z: 0.78
        orientation:
          x: 0.0
          y: -1.0
          z: 0.0
          w: 0.0

    marker_8:
      pose:
        position:
          x: 3.17
          y: 0.00
          z: 0.55
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_9:
      pose:
        position:
          x: 7.49
          y: -0.35
          z: 0.78
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    # marker_10:
    #   pose:
    #     position:
    #       x: 6.21
    #       y: -0.18
    #       z: 0.78
    #     orientation:
    #       x: -0.3536
    #       y: -0.8536
    #       z:  0.1464
    #       w:  0.3536

    marker_10:
      pose:
        position:
          x: 6.21
          y: 0.18
          z: 0.78
        orientation:
          x: 0.0
          y: -0.70710678
          z: -0.70710678
          w: 0.0

    marker_11:
      pose:
        position:
          x: 6.00
          y: 0.00
          z: 0.78
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    # marker_12:
    #   pose:
    #     position:
    #       x: 6.21
    #       y: 0.18
    #       z: 0.78
    #     orientation:
    #       x:  0.3536
    #       y: -0.8536
    #       z: -0.1464
    #       w:  0.3536
  
    marker_12:
      pose:
        position:
          x: 6.21
          y: -0.18
          z: 0.78
        orientation:
          x: 0.70710678
          y: 0.0
          z: 0.0
          w: 0.70710678

    marker_13:
      pose:
        position:
          x: 3.92
          y: 0.00
          z: 0.96
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_15:
      pose:
        position:
          x: 4.68
          y: 0.00
          z: 0.90
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5

    marker_18: 
      pose:
        position:
          x: 7.49
          y: 0.35
          z: 0.78
        orientation:
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5
