

tello/control/teleop_twist_joy:
  ros__parameters:
    #axis mapping
    "axis_linear.x": 4
    "axis_linear.y": 3
    "axis_linear.z": 1
    "axis_angular.yaw": 0

    #axis scaling normal
    "scale_linear.x": 0.5
    "scale_linear.y": 0.5
    "scale_linear.z": 0.1
    "scale_angular.yaw": 0.2

    #axis scaling turbo
    "scale_linear_turbo.x": 1.0
    "scale_linear_turbo.y": 1.0
    "scale_linear_turbo.z": 1.0
    "scale_angular_turbo.yaw": 1.0

    #other
    "require_enable_button": True
    "enable_button": 5
    "enable_turbo_button": 4
    "inverted_reverse": False
    "publish_stamped_twist": True
    "frame": 'base_link'